[package]
name = "memo"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = "0.10.2"
borsh-derive = "0.10.2"
solana-program = "1.16"

[dev-dependencies]
solana-program-test = "1.16"
solana-sdk = "1.16"

[lib]
crate-type = ["cdylib", "lib"]